/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

/**
 *
 * @author ASUS TUF
 */
public class doctorpage extends javax.swing.JFrame {

    /**
     * Creates new form doctorpage
     */
    public doctorpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JADWAL = new javax.swing.JButton();
        DAFTARPASIEN = new javax.swing.JButton();
        KEMBALI = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JADWAL.setBackground(new java.awt.Color(69, 143, 246));
        JADWAL.setForeground(new java.awt.Color(255, 255, 255));
        JADWAL.setText("Atur Jadwal");
        JADWAL.setBorder(null);
        JADWAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JADWALActionPerformed(evt);
            }
        });
        getContentPane().add(JADWAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 120, 40));

        DAFTARPASIEN.setBackground(new java.awt.Color(69, 143, 246));
        DAFTARPASIEN.setForeground(new java.awt.Color(255, 255, 255));
        DAFTARPASIEN.setText("Lihat Sekarang");
        DAFTARPASIEN.setBorder(null);
        DAFTARPASIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAFTARPASIENActionPerformed(evt);
            }
        });
        getContentPane().add(DAFTARPASIEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 660, 120, 40));

        KEMBALI.setText("Kembali");
        getContentPane().add(KEMBALI, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiuxfix/doctor page.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 0, 1144, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JADWALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JADWALActionPerformed
        sceduledoktor sch = new sceduledoktor();
        sch.setVisible(true);
    }//GEN-LAST:event_JADWALActionPerformed

    private void DAFTARPASIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAFTARPASIENActionPerformed
        ViewPatient sch = new ViewPatient();
        sch.setVisible(true);
    }//GEN-LAST:event_DAFTARPASIENActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctorpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DAFTARPASIEN;
    private javax.swing.JButton JADWAL;
    private javax.swing.JButton KEMBALI;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
