/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS TUF
 */
public class login extends javax.swing.JFrame {

    private final Connection conn;

    /**
     * Creates new form LOGIN
     */
    public login() {
        initComponents();
        conn = SQLConnector.getConnection();
        showDoctor();
        showPatient();
    }
    
     public void showDoctor() {
        try {
            String sql = "SELECT username, name FROM doctors WHERE username = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, "Input your name here");
            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                String name = rs.getString("name");
                String username = rs.getString("username");
                USERNAME.setText(name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HospitalReservationApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    public void showPatient() {
        try {
            String sql = "SELECT username, name FROM patients WHERE username = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, "Input your name here");
            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                String name = rs.getString("name");
                String username = rs.getString("username");
                USERNAME.setText(name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HospitalReservationApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        USERNAME = new javax.swing.JTextField();
        PATIENT = new javax.swing.JButton();
        DOCTOR = new javax.swing.JButton();
        REGISTER = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USERNAME.setText("Username");
        USERNAME.setBorder(null);
        USERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 330, 40));

        PATIENT.setBackground(new java.awt.Color(80, 39, 121));
        PATIENT.setForeground(new java.awt.Color(255, 255, 255));
        PATIENT.setText("Patient");
        PATIENT.setBorder(null);
        PATIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PATIENTActionPerformed(evt);
            }
        });
        getContentPane().add(PATIENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 330, 40));

        DOCTOR.setBackground(new java.awt.Color(80, 39, 121));
        DOCTOR.setForeground(new java.awt.Color(255, 255, 255));
        DOCTOR.setText("Doctor");
        DOCTOR.setBorder(null);
        DOCTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOCTORActionPerformed(evt);
            }
        });
        getContentPane().add(DOCTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 330, 40));

        REGISTER.setBackground(new java.awt.Color(173, 83, 166));
        REGISTER.setForeground(new java.awt.Color(255, 255, 255));
        REGISTER.setText("Register");
        REGISTER.setBorder(null);
        REGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERActionPerformed(evt);
            }
        });
        getContentPane().add(REGISTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 760, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiuxfix/2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1392, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAMEActionPerformed

    private void PATIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PATIENTActionPerformed
        try {
            String sql = "SELECT COUNT(*) FROM patients WHERE username = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            String username = USERNAME.getText();
            st.setString(1, username);
            ResultSet resultSet = st.executeQuery();
            
            resultSet.next();
            int count = resultSet.getInt(1);

            if (count > 0) {
                JOptionPane.showMessageDialog(null, "Login Successful!");
                pagepatient pagepat = new pagepatient();
                pagepat.setVisible(true);
            } else{
                JOptionPane.showMessageDialog(null, "Username doesn't exists.");
                login Log = new login();
                Log.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HospitalReservationApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PATIENTActionPerformed

    private void REGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERActionPerformed
        Register register = new Register();
        register.setVisible(true);
    }//GEN-LAST:event_REGISTERActionPerformed

    private void DOCTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOCTORActionPerformed
        try {
            String sql = "SELECT COUNT(*) FROM doctors WHERE username = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            String username = USERNAME.getText();
            st.setString(1, username);
            ResultSet resultSet = st.executeQuery();
            
            resultSet.next();
            int count = resultSet.getInt(1);

            if (count > 0) {
                JOptionPane.showMessageDialog(null, "Login Successful!");
                doctorpage Doc = new doctorpage();
                Doc.setVisible(true);;
            } else{
                JOptionPane.showMessageDialog(null, "Username doesn't exists.");
                login Log = new login();
                Log.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HospitalReservationApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DOCTORActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DOCTOR;
    private javax.swing.JButton PATIENT;
    private javax.swing.JButton REGISTER;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
