/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Time;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS TUF
 */
public class sceduledoktor extends javax.swing.JFrame {
    private static Connection conn;
    /**
     * Creates new form sceduledoktor
     */
    public sceduledoktor() {
        initComponents();
        conn = SQLConnector.getConnection();
        showschedule();
    }
    
    public void showschedule() {
    try {
        String sql = "SELECT username, session_start_time, session_end_time FROM doctor_availability WHERE username = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, "Input your name here");
        ResultSet rs = st.executeQuery();

        if (rs.next()) {
            String username = rs.getString("username");
            Time startTime = rs.getTime("session_start_time");
            Time endTime = rs.getTime("session_end_time");

            Username.setText(username);
            Start.setText(startTime.toString());
            End.setText(endTime.toString());
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(HospitalReservationApp.class.getName()).log(Level.SEVERE, null, ex);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Start = new javax.swing.JTextField();
        End = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        SUBMIT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Start.setText("Start");
        getContentPane().add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 460, 40));

        End.setText("End");
        End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndActionPerformed(evt);
            }
        });
        getContentPane().add(End, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 460, 40));

        Username.setText("Username");
        Username.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                UsernameInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 460, 40));

        SUBMIT.setBackground(new java.awt.Color(0, 0, 0));
        SUBMIT.setForeground(new java.awt.Color(255, 255, 255));
        SUBMIT.setText("SUBMIT");
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });
        getContentPane().add(SUBMIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 200, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiuxfix/set_scheduke.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndActionPerformed

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITActionPerformed
      try {
        String sql = "INSERT INTO doctor_availability(doctor_username, session_start_time, session_end_time) VALUES (?, ?, ?)";
        PreparedStatement st = conn.prepareStatement(sql);

        String username = Username.getText();
        String startText = Start.getText();
        String endText = End.getText();

        // Parse the time values into java.sql.Time objects
        Time startTime = Time.valueOf(startText);
        Time endTime = Time.valueOf(endText);

        long intervalMillis = 30 * 60 * 1000; // 30 minutes in milliseconds

        // Iterate through the time range in 30-minute intervals
        for (long timeMillis = startTime.getTime(); timeMillis < endTime.getTime(); timeMillis += intervalMillis) {
            Time sessionStart = new Time(timeMillis);
            Time sessionEnd = new Time(timeMillis + intervalMillis);

            st.setString(1, username);
            st.setTime(2, sessionStart);
            st.setTime(3, sessionEnd);

            int rowsAffected = st.executeUpdate();

            if (rowsAffected <= 0) {
                // Handle insertion failure
                JOptionPane.showMessageDialog(this, "Error adding schedule. Please check your input and try again.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit the loop if insertion fails
            }
        }

        JOptionPane.showMessageDialog(this, "Schedule added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        doctorpage Doc = new doctorpage();
        Doc.setVisible(true);
        
    } catch (SQLException ex) {
        Logger.getLogger(HospitalReservationApp.class.getName()).log(Level.SEVERE, null, ex);
        // SQL Exception (error)
        JOptionPane.showMessageDialog(this, "Error adding schedule. Please check your username and try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }                                      
    }//GEN-LAST:event_SUBMITActionPerformed
    
    private void UsernameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_UsernameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sceduledoktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sceduledoktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sceduledoktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sceduledoktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sceduledoktor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField End;
    private javax.swing.JButton SUBMIT;
    private javax.swing.JTextField Start;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
